<?php

/**
 * PluginFsMenuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFsMenuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFsMenuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFsMenu');
    }
}